# This workflow will test the package with pytest and upload the coverage report to CodeCov
# for every commit pushed to any branch. Also, CodeCov will add a comment about the coverage to the PR.

name: test_coverage

on: [push, pull_request]

jobs:
  test_coverage:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create a virtual environment
        run: python -m venv venv

      - name: Activate the virtual environment
        run: source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install ".[all]" ".[dev]"

      - name: Run tests
        run: |
          python -m pytest --cov=sign_language_translator --cov-report=xml --cov-report=term

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
